# Generated by Django 4.1.7 on 2023-03-19 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField(max_length=20)),
                ('end_time', models.TimeField(max_length=20)),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('admin_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('รออนุมัติ', 'รออนุมัติ'), ('ไม่อนุมัติ', 'ไม่อนุมัติ'), ('อนุมัติ', 'อนุมัติ')], default='รออนุมัติ', max_length=20)),
                ('date_add', models.DateField(auto_now=True)),
                ('time_add', models.TimeField(auto_now=True)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_room', to='myapp_admin.myroom')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'booking',
            },
        ),
    ]
