# Generated by Django 4.1.7 on 2023-03-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_user', '0002_booking_line_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_user_id', models.CharField(max_length=50, unique=True)),
                ('django_user_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
