# Generated by Django 4.1.7 on 2023-03-26 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_user', '0003_lineuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LineUser',
        ),
    ]
