# Generated by Django 4.1.7 on 2023-03-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_user', '0006_booking_line_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='line_user',
        ),
        migrations.AddField(
            model_name='booking',
            name='line_user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
