# Generated by Django 4.1.7 on 2023-03-29 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_user', '0007_remove_booking_line_user_booking_line_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-date', '-start_time']},
        ),
    ]
