# Generated by Django 4.1.7 on 2023-03-29 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_user', '0008_alter_booking_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
    ]
