# Generated by Django 4.1.7 on 2023-03-19 22:40

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('เปิด', 'เปิด'), ('ปิด', 'ปิด')], default='เปิด', max_length=100)),
            ],
            options={
                'db_table': 'room',
            },
        ),
    ]
